### ISSUE TITLE
Suggestion to use php7-apcu

### ISSUE THREAD

**Issue by andypost** [dminca/drupal-docker#48]
use php7-apcu package from testing alpine
core using it by default https://www.drupal.org/node/2327507

PS: php7-ssh2 coming https://github.com/alpinelinux/aports/pull/139

**Comment by dminca** [comment]
That's great news @andypost ! Thank you very much :smile:

Is `php7-apcu` used for caching only?

**Comment by andypost** [comment]
yep, opcache for code

**Comment by dminca** [comment]
Support for `php7-apcu` granted starting from release [v1.1.2](https://github.com/dminca/drupal-docker/tree/v1.1.2)
Details in #53
