### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by magick93** [dminca/drupal-docker#50]
Hello

* **Version**: Docker version 1.11.2, build b9f10c9
* **Platform**: Ubuntu 15.04

When I try to run this docker compose project, using either postges or msql, neither will achieves a database connection when installing drupal.

![selection_546](https://cloud.githubusercontent.com/assets/2173213/16353321/d5f66f38-3a78-11e6-9199-b9f765034215.png)

**Comment by dminca** [comment]
Hello @magick93 and thanks for the detailed bug report!

Please tell me what **Database Host** did you enter, after clicking the **ADVANCED OPTIONS** section  (above the _Save and continue_ button)

**Comment by dminca** [comment]
I've replicated the bug, and the _reason_ you're getting that error is that the container is running on **PostgreSQL** by default.

I suggest you select the **PostgreSQL** option, and then continue entering the default credentials:
**drupal** for all 3 fields, then click **Advanced options** and add the `drupaldocker_psql_1` in the **Database Host** field.

> You can get the **database host** by typing `docker ps` and checking the **NAME** row for **...psql...**

**Comment by dminca** [comment]
Fix released under tag [**v1.1.1**][1] :+1: 

[1]: https://github.com/dminca/drupal-docker/releases/tag/v1.1.1
